[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.19"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

[dependencies]
forge-std = { git = "https://github.com/foundry-rs/forge-std", tag = "v1.6.0" }
openzeppelin-contracts = { git = "https://github.com/OpenZeppelin/openzeppelin-contracts", tag = "v4.9.3" }

[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true

[rpc_endpoints]
mainnet = "${ETHEREUM_RPC}"
optimism = "${OPTIMISM_RPC}"
arbitrum = "${ARBITRUM_RPC}"
polygon = "${POLYGON_RPC}"
base = "${BASE_RPC}"
gnosis = "${GNOSIS_RPC}"
celo = "${CELO_RPC}"

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
optimism = { key = "${OPTIMISTIC_ETHERSCAN_API_KEY}" }
arbitrum = { key = "${ARBISCAN_API_KEY}" }
polygon = { key = "${POLYGONSCAN_API_KEY}" }
base = { key = "${BASESCAN_API_KEY}" }
gnosis = { key = "${GNOSIS_ETHERSCAN_API_KEY}" }
celo = { key = "${CELOSCAN_API_KEY}" }
